### ISSUE TITLE
如果路由的界面需要先登录

### ISSUE THREAD

**Issue by FutureChen** [Huohua/HHRouter#20]
比如我的优惠券之类的界面，需要用户登录才能查看，这种情况下该如果操作

**Comment by lightory** [comment]
这部分逻辑应该由对应界面的 ViewController 管理。

**Comment by FutureChen** [comment]
如果由 vc来管理的话 跳转的顺序就变成这样了
       1.  路由=>优惠券VC=>登录VC
如何达到下面的效果

              =>（如果未登录）登录VC=>优惠券VC
      2·路由
             =>（如果登录)优惠券VC

**Comment by FutureChen** [comment]
- -。其实我也觉得需要 VC 来管理。恩

**Comment by lightory** [comment]
我惯用的做法是这样的：
1. 进入优惠券 VC 时，如果检测到未登录，modal present 登录 VC。
2. 在登陆 VC，登陆成功后，dismiss。

**Comment by FutureChen** [comment]
谢
